sudo: false
language: java
jdk:
  - openjdk7
install: 
    # download Cloud SDK
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-118.0.0-linux-x86_64.tar.gz
  - tar -xzvf google-cloud-sdk-118.0.0-linux-x86_64.tar.gz
  - export PATH=$PWD/google-cloud-sdk/bin:$PATH
  - export CLOUDSDK_CORE_DISABLE_USAGE_REPORTING=true
  # update all Cloud SDK components
  - gcloud components update --quiet
  # add App Engine component to Cloud SDK
  - gcloud components install app-engine-java --quiet
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - mvn -Ptravis --fail-at-end verify
  - jdk_switcher use oraclejdk8
  - mvn -Ptravis --fail-at-end verify -Declipse.target=neon
cache:
  directories:
   - $HOME/.m2

