sudo: false
language: java
addons:
  apt:
    packages:
      - metacity
before_install:
  # change reference from now-defunct maven repository (#1406)
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
install: 
  # use mvn â‰¥ 3.3.9 to ensure faulty test exit states fail the build (#1276)
  - mvn -B -N io.takari:maven:wrapper -Dmaven=3.5.0
  # download and install Cloud SDK (may be cached)
  - build/install-cloudsdk.sh 190.0.1 $HOME
# ECLIPSE_TARGET is the targeted platform: photon is the default target
# We run jacoco on photon
matrix:
  include:
    - name: "Eclipse Oxygen (4.7) on Java 8"
      jdk: oraclejdk8
      env: ECLIPSE_TARGET=oxygen
    - name: "Eclipse Photon (4.8) on Java 8"
      jdk: oraclejdk8
      env: MAVEN_FLAGS='-Pjacoco'
    - name: "Eclipse 2018-09 (4.9) on Java 8"
      jdk: oraclejdk8
      env: ECLIPSE_TARGET=2018-09
    - name: "Eclipse 2018-09 (4.9) on Java 11"
      jdk: openjdk11
      env: ECLIPSE_TARGET=2018-09 MAVEN_FLAGS='--toolchains=.travisci/toolchains.xml'
    - name: "Eclipse 2018-12 (4.10) on Java 11"
      jdk: openjdk11
      env: ECLIPSE_TARGET=2018-12 MAVEN_FLAGS='--toolchains=.travisci/toolchains.xml'
env:
  global:
    - CLOUD_SDK_HOME=$HOME/google-cloud-sdk
    - PATH=$CLOUD_SDK_HOME/bin:$PATH
    # -Xmx700m: Our maven build typically reports about 512m required
    # -DshowDateTime: show milliseconds since start
    - MAVEN_OPTS='-Xmx700m -Dorg.slf4j.simpleLogger.showDateTime=true'
    - CLOUDSDK_CORE_DISABLE_USAGE_REPORTING=true
    - DISPLAY=:99.0
    - GCS_BUILD_BUCKET=gs://travis_artifacts
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - metacity --sm-disable --replace &
  - sleep 3 # give metacity some time to start
script: ./mvnw -V -B --fail-at-end verify ${MAVEN_FLAGS}
     -Ptravis -Derrorprone
     ${ECLIPSE_TARGET:+-Declipse.target=${ECLIPSE_TARGET}}
cache:
  directories:
   - $HOME/.m2
   - $CLOUD_SDK_HOME
after_success:
  # test req'd as we don't run coverage on all elements of the matrix
  - if [ -d build/jacoco/target ]; then bash <(curl -s https://codecov.io/bash); fi
after_script:
  # Upload build reports to our Google Cloud Storage bucket (only available
  # for team PRs).  This is done in two steps:
  #   1. Copy surefire-reports and screenshots.
  #   2. Copy build results (if successful). This step is conditioned
  #      on jacoco as we already ensure jacoco is only performed
  #      for a single element of the build matrix.
  - if [ "$TRAVIS_SECURE_ENV_VARS" = true ]; then
      openssl aes-256-cbc -K $encrypted_7e6c351b4cee_key -iv $encrypted_7e6c351b4cee_iv
        -in .travisci/travis-service-account.json.enc -out /tmp/travis-service-account.json -d;
      BUILDTIMESTAMP=`date '+%Y%m%d-%H%M'`;
      $CLOUD_SDK_HOME/bin/gcloud auth activate-service-account --key-file=/tmp/travis-service-account.json;
      mkdir build-results && .travisci/copy-test-results.sh plugins build-results;
      $CLOUD_SDK_HOME/bin/gsutil -m -q
        cp -r -z 'txt,xml,html' -a public-read
          build-results/*
          $GCS_BUILD_BUCKET/travis/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}-${TRAVIS_OS_NAME}-${BUILDTIMESTAMP}/;
      if [ -d gcp-repo/target/repository -a -d build/jacoco/target ]; then
        $CLOUD_SDK_HOME/bin/gsutil -m -q
          cp -r -z 'txt,xml,html' -a public-read
            gcp-repo/target/repository/*
            $GCS_BUILD_BUCKET/travis/${TRAVIS_BUILD_NUMBER}/repository/;
      fi;
    fi
