sudo: false
language: java
before_install:
  # change reference from now-defunct maven repository
  # (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1406)
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
install: 
  # use 3.3.9 to ensure faulty test exit states fail the build (#1276)
  - mvn -N io.takari:maven:wrapper -Dmaven=3.3.9
  # download Cloud SDK
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-139.0.1-linux-x86_64.tar.gz
  - tar -xzf google-cloud-sdk-139.0.1-linux-x86_64.tar.gz
  # update all Cloud SDK components
  - gcloud components update --quiet
  # add App Engine component to Cloud SDK
  - gcloud components install app-engine-java --quiet
env:
  global:
    - PATH=$PWD/google-cloud-sdk/bin:$PATH
    - CLOUDSDK_CORE_DISABLE_USAGE_REPORTING=true
    - DISPLAY=:99.0
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - metacity --sm-disable --replace &
  - sleep 3 # give metacity some time to start
# mars is the default target
matrix:
  include:
  - jdk: openjdk7
  - jdk: oraclejdk8
    env: ECLIPSE_TARGET=neon
  - jdk: oraclejdk8
    env: ECLIPSE_TARGET=oxygen MAVEN_FLAGS=-Pjacoco
script: ./mvnw -Ptravis --fail-at-end verify ${ECLIPSE_TARGET:+-Declipse.target=${ECLIPSE_TARGET}} ${MAVEN_FLAGS}
addons:
  apt:
    packages:
      - metacity
cache:
  directories:
   - $HOME/.m2
after_success:
  # test req'd as we don't run coverage on all elements of the matrix
  - if [ -d build/jacoco/target ]; then bash <(curl -s https://codecov.io/bash); fi
